package net.ltfc.chinaartgallery.base.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchKeyDaoConfig;

    private final SearchKeyDao searchKeyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchKeyDaoConfig = daoConfigMap.get(SearchKeyDao.class).clone();
        searchKeyDaoConfig.initIdentityScope(type);

        searchKeyDao = new SearchKeyDao(searchKeyDaoConfig, this);

        registerDao(SearchKey.class, searchKeyDao);
    }
    
    public void clear() {
        searchKeyDaoConfig.getIdentityScope().clear();
    }

    public SearchKeyDao getSearchKeyDao() {
        return searchKeyDao;
    }

}
