package net.ltfc.chinaartgallery.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.ltfc.chinaartgallery.model.db.SearchSuggestion;

import net.ltfc.chinaartgallery.model.db.SearchSuggestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchSuggestionDaoConfig;

    private final SearchSuggestionDao searchSuggestionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchSuggestionDaoConfig = daoConfigMap.get(SearchSuggestionDao.class).clone();
        searchSuggestionDaoConfig.initIdentityScope(type);

        searchSuggestionDao = new SearchSuggestionDao(searchSuggestionDaoConfig, this);

        registerDao(SearchSuggestion.class, searchSuggestionDao);
    }
    
    public void clear() {
        searchSuggestionDaoConfig.getIdentityScope().clear();
    }

    public SearchSuggestionDao getSearchSuggestionDao() {
        return searchSuggestionDao;
    }

}
