package net.ltfc.chinaartgallery.model.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEARCH_KEY".
 */
public class SearchKey {

    private Long id;
    private String key;
    private java.util.Date date;

    public SearchKey() {
    }

    public SearchKey(Long id) {
        this.id = id;
    }

    public SearchKey(Long id, String key, java.util.Date date) {
        this.id = id;
        this.key = key;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
